steps:
  # Build and push container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/image-uploader:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/image-uploader:$COMMIT_SHA']

  # Deploy Blue (50% traffic)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'image-uploader'
      - '--image=gcr.io/$PROJECT_ID/image-uploader:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--update-env-vars=GCS_BUCKET_NAME=$_BUCKET_NAME,DEPLOYMENT_COLOR=blue,APP_VERSION=$_VERSION'
      - '--revision-suffix=blue-$_VERSION'
      - '--no-traffic'

  # Deploy Green (50% traffic)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'image-uploader'
      - '--image=gcr.io/$PROJECT_ID/image-uploader:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--update-env-vars=GCS_BUCKET_NAME=$_BUCKET_NAME,DEPLOYMENT_COLOR=green,APP_VERSION=$_VERSION'
      - '--revision-suffix=green-$_VERSION'
      - '--no-traffic'

  # Split traffic 50/50
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'services'
      - 'update-traffic'
      - 'image-uploader'
      - '--region=us-central1'
      - '--to-revisions=image-uploader-blue-$_VERSION=50,image-uploader-green-$_VERSION=50'

substitutions:
  _BUCKET_NAME: cnd2geminiai-images-buckets
  _VERSION: v1-0-0  # Update this for each release
  PROJECT_ID: image-upload-gcp-project
