options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Build container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/image-uploader:$_VERSION', '.']
    id: 'build'
  
  # Push container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/image-uploader:$_VERSION']
    id: 'push'
    waitFor: ['build']

  # Deploy blue
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'image-uploader'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/image-uploader:$_VERSION'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--set-env-vars=GCS_BUCKET_NAME=$_BUCKET_NAME,DEPLOYMENT_COLOR=blue,APP_VERSION=$_VERSION'
      - '--revision-suffix=blue-$_VERSION'
      - '--memory=512Mi'
      - '--cpu=1'
    id: 'deploy-blue'
    waitFor: ['push']

  # Deploy green
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'image-uploader'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/image-uploader:$_VERSION'
      - '--region=us-central1'
      - '--platform=managed'
      - '--no-traffic'
      - '--set-env-vars=GCS_BUCKET_NAME=$_BUCKET_NAME,DEPLOYMENT_COLOR=green,APP_VERSION=$_VERSION'
      - '--revision-suffix=green-$_VERSION'
      - '--memory=512Mi'
      - '--cpu=1'
    id: 'deploy-green'
    waitFor: ['deploy-blue']

  # Split traffic
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'services'
      - 'update-traffic'
      - 'image-uploader'
      - '--region=us-central1'
      - '--to-revisions=image-uploader-blue-$_VERSION=50,image-uploader-green-$_VERSION=50'
    id: 'split-traffic'
    waitFor: ['deploy-green']
